version: '2'

services:
  hello:
    image: nginx
    container_name: nginx
    ports: ["80:80"]
    volumes: ["./www:/usr/share/nginx/html:ro"]

  linkerd:
    image: buoyantio/linkerd
    container_name: linkerd
    ports: ["4140:4140", "9990:9990"]
    volumes: ["./linkerd.yaml:/io.buoyant/linkerd.yaml:ro"]
    command: /io.buoyant/linkerd.yaml

  namerd:
    image: buoyantio/namerd
    container_name: namerd
    ports: ["4100:4100", "4181:4181"]
    volumes: ["./namerd.yaml:/io.buoyant/namerd.yaml:ro"]
    command: /io.buoyant/namerd.yaml

  etcd:
    image: quay.io/coreos/etcd
    container_name: etcd
    ports: ["2379:2379"]
    command: ["etcd","-advertise-client-urls", "http://etcd:2379", "-listen-client-urls", "http://0.0.0.0:2379"]
